### ISSUE TITLE
Hackage version no longer compatible with recent dependencies

### ISSUE THREAD

**Issue by tsahyt** [mr/reactive-banana-gi-gtk#1]
The version published on Hackage has version bounds on `reactive-banana` (1.2.0.0 is the most recent on Hackage at this time) and the haskell-gi packages (e.g. `haskell-gi-base`, which is now at 0.21.1, with `gi-gtk` depending on 0.21.*) that keep it from building against the most recent versions. The cabal file in this repository does not have these bounds, and builds just fine. I've tested it a bit and it seems to work fine, so this might only be a matter of bumping some version bounds and pushing it to Hackage.

**Comment by mr** [comment]
Yeah it should be OK to do that. Either send me a PR or I'll get to it later today.

**Comment by concavegit** [comment]
Now that the pull request is merged, when can the package be updated on hackage/stackage?

**Comment by mr** [comment]
Sorry to keep you waiting so long, but I've been having build issues and haven't had time to work on it. I'm trying to get to it now.

**Comment by mr** [comment]
I've been trying to build with the latest LTS from stackage (stack.yml requires some updates but it's pretty simple). For anyone interested I'll post some of the errors I'm getting. I'll continue working but I figure it might help if people are interested.

    /home/mattro/workspace/reactive-banana-gi-gtk/example/app/Main.hs:45:17: error:
        • Couldn't match type ‘haskell-gi-base-0.21.1:Data.GI.Base.Signals.HaskellCallbackType
                                 (haskell-gi-base-0.21.1:Data.GI.Base.Overloading.FindElement
                                    "destroy"
                                    (haskell-gi-base-0.21.1:Data.GI.Base.Overloading.SignalList Window)
                                    (((('GHC.TypeLits.Text "Unknown signal \8216"
                                        'GHC.TypeLits.:<>: 'GHC.TypeLits.Text "destroy")
                                       'GHC.TypeLits.:<>: 'GHC.TypeLits.Text "\8217 for object \8216")
                                      'GHC.TypeLits.:<>: 'GHC.TypeLits.ShowType Window)
                                     'GHC.TypeLits.:<>: 'GHC.TypeLits.Text "\8217."))’
                         with ‘IO ()’
            arising from a use of ‘signalE0’
        • In a stmt of a 'do' block: destroyE <- signalE0 window #destroy
          In the expression:
            do b <- builderNew
               builderAddFromFile b "test.ui"
               window <- castB b "window" Window
               destroyE <- signalE0 window #destroy
               ....
          In an equation for ‘networkDescription’:
              networkDescription
                = do b <- builderNew
                     builderAddFromFile b "test.ui"
                     window <- castB b "window" Window
                     ....
       |
    45 |     destroyE <- signalE0 window #destroy
       |                 ^^^^^^^^^^^^^^^^^^^^^^^^
```

    /home/mattro/workspace/reactive-banana-gi-gtk/example/app/Main.hs:49:17: error:
        • Type ‘Stack’ does not have any known attributes.
        • In a stmt of a 'do' block:
            visibleB <- attrB stack #visibleChildName
          In the expression:
            do b <- builderNew
               builderAddFromFile b "test.ui"
               window <- castB b "window" Window
               destroyE <- signalE0 window #destroy
               ....
          In an equation for ‘networkDescription’:
              networkDescription
                = do b <- builderNew
                     builderAddFromFile b "test.ui"
                     window <- castB b "window" Window
                     ....
       |
    49 |     visibleB <- attrB stack #visibleChildName
       |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    /home/mattro/workspace/reactive-banana-gi-gtk/example/app/Main.hs:65:25: error:
        • Type ‘Label’ does not have any known attributes.
        • In the expression: #label :== showT <$> searchCount
          In the second argument of ‘sink’, namely
            ‘[#label :== showT <$> searchCount]’
          In a stmt of a 'do' block:
            sink searchedLabel [#label :== showT <$> searchCount]
       |
    65 |     sink searchedLabel [#label :== showT <$> searchCount]
       |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by mr** [comment]
Both looks like it can't find any properties or signals, which seems odd. I might just have dependency issues.

**Comment by mr** [comment]
Upon further inspection it looks like the overloaded labels get disabled on the latest stackage LTS because of a bug in GHC. I'm updating to the nightly and am trying to build again.

**Comment by mr** [comment]
Ok everything built correctly and I've uploaded the new version to Hackage. Reopen if there are any issues.
