### ISSUE TITLE
Can not bind to #keyPressedEvent

### ISSUE THREAD

**Issue by MuratOzsoyler** [mr/reactive-banana-gi-gtk#3]
I can not bind to `keyPressedEvent` of `Gtk.Widget`. Getting this error:
```
Couldn't match type `Bool' with `()'
        arising from a use of `signalE1'
    * In a stmt of a 'do' block:
        keyPressE <- signalE1 entry #keyPressEvent
```

This is due to `Handler` is defined as `type Handler a = a -> IO ()`
 
Is there a way to bind to this event or feed the keys into the network?

**Comment by mr** [comment]
I'll have to make a change to void the callback when using it with reactive-banana. Shouldn't be too hard. I can get back to you about this maybe later today or tomorrow depending on time.

You could also try making the change yourself here: https://github.com/mr/reactive-banana-gi-gtk/blob/master/reactive-banana-gi-gtk/src/Reactive/Banana/GI/Gtk.hs#L94

(and then changing the type signatures to work with `a -> IO b`).

**Comment by MuratOzsoyler** [comment]
Thank you for the prompt response.

Actually I am new to Haskell and I tried `(a -> IO b) versions of the functions you pointed to. But got some errors that I couldn't cope with.

Instead I am trying this:
```
        (keyPressE, keyPressEFire) <- newEvent :: MomentIO (Event Gdk.EventKey, Handler Gdk.EventKey)
        on entry #keyPressEvent $ \e -> do
            keyPressEFire e
            return False
```

I shall see whether it works if my battery live a bit longer.

**Comment by mr** [comment]
Sadly I'm not at my computer, but I'm pretty sure my idea will work. I'll
just have to give it a shot later.

**Comment by mr** [comment]
So it turns out the solution was a little more involved. I've added some new functions called `signalE0R` and `signalE1R` (the R is for 'return'). These let you return values to the GTK callback. Here's the commit: https://github.com/mr/reactive-banana-gi-gtk/commit/44a6f41a3b690a4be01eb5be8c074e7086705377

You should be able to get it in hackage under version 0.4.0.0
